//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace ClosedXML.Report.Tests.TestModels
{
    /// <summary>
    /// Database       : dbdemos
    /// Data Source    : ..\..\DB\dbdemos.mdb
    /// Server Version : 04.00.0000
    /// </summary>
    public partial class DbDemos : LinqToDB.Data.DataConnection
    {
        public ITable<Country> countries { get { return this.GetTable<Country>(); } }
        public ITable<Customer> customers { get { return this.GetTable<Customer>(); } }
        public ITable<Employee> employees { get { return this.GetTable<Employee>(); } }
        public ITable<Item> items { get { return this.GetTable<Item>(); } }
        public ITable<NextCust> nextcusts { get { return this.GetTable<NextCust>(); } }
        public ITable<NextItem> nextitems { get { return this.GetTable<NextItem>(); } }
        public ITable<NextOrd> nextords { get { return this.GetTable<NextOrd>(); } }
        public ITable<Order> orders { get { return this.GetTable<Order>(); } }
        public ITable<Part> parts { get { return this.GetTable<Part>(); } }
        public ITable<Vendor> vendors { get { return this.GetTable<Vendor>(); } }

        public DbDemos()
        {
            UpdateMappingSchema();
        }

        public DbDemos(string configuration)
            : base(configuration)
        {
            UpdateMappingSchema();
        }

        private void UpdateMappingSchema()
        {
            this.MappingSchema.SetConverter<long, DateTime?>(ticks => new DateTime(ticks, DateTimeKind.Unspecified));
            this.MappingSchema.SetConverter<string, DateTime?>(ticks =>
            {
                if (string.IsNullOrEmpty(ticks))
                {
                    return null;
                }
                return DateTime.Parse(ticks);
            });
        }
    }

    [Table("country")]
    public partial class Country
    {
        [PrimaryKey, Nullable]
        public string Name { get; set; } // text(24)
        [Column, Nullable]
        public string Capital { get; set; } // text(24)
        [Column, Nullable]
        public string Continent { get; set; } // text(24)
        [Column, Nullable]
        public double? Area { get; set; } // Double
        [Column, Nullable]
        public double? Population { get; set; } // Double
    }

    [Table("customer")]
    public partial class Customer
    {
        [PrimaryKey, Identity]
        public int CustNo { get; set; } // int
        [Column, Nullable]
        public string Company { get; set; } // text(30)
        [Column, Nullable]
        public string Addr1 { get; set; } // text(30)
        [Column, Nullable]
        public string Addr2 { get; set; } // text(30)
        [Column, Nullable]
        public string City { get; set; } // text(15)
        [Column, Nullable]
        public string State { get; set; } // text(20)
        [Column, Nullable]
        public string Zip { get; set; } // text(10)
        [Column, Nullable]
        public string Country { get; set; } // text(20)
        [Column, Nullable]
        public string Phone { get; set; } // text(15)
        [Column, Nullable]
        public string Fax { get; set; } // text(15)
        [Column, Nullable]
        public double? TaxRate { get; set; } // Double
        [Column, Nullable]
        public string Contact { get; set; } // text(20)
        [Column, Nullable]
        public DateTime? LastInvoiceDate { get; set; } // DateTime
    }

    [Table("employee")]
    public partial class Employee
    {
        [PrimaryKey, Nullable]
        public int? EmpNo { get; set; } // Long
        [Column, Nullable]
        public string LastName { get; set; } // text(20)
        [Column, Nullable]
        public string FirstName { get; set; } // text(15)
        [Column, Nullable]
        public string PhoneExt { get; set; } // text(4)
        [Column, Nullable]
        public DateTime? HireDate { get; set; } // DateTime
        [Column, Nullable]
        public double? Salary { get; set; } // Double
    }

    [Table("items")]
    public partial class Item
    {
        [PrimaryKey(1), Nullable]
        public double? OrderNo { get; set; } // Double
        [PrimaryKey(2), Nullable]
        public double? ItemNo { get; set; } // Double
        [Column, Nullable]
        public double? PartNo { get; set; } // Double
        [Column, Nullable]
        public int Qty { get; set; } // Long
        [Column, Nullable]
        public double Discount { get; set; } // Double
    }

    [Table("nextcust")]
    public partial class NextCust
    {
        [Column, Nullable]
        public double? NewCust { get; set; } // Double
    }

    [Table("nextitem")]
    public partial class NextItem
    {
        [Column, Nullable]
        public double? NewKey { get; set; } // Double
    }

    [Table("nextord")]
    public partial class NextOrd
    {
        [Column, Nullable]
        public double? NewKey { get; set; } // Double
    }

    [Table("orders")]
    public partial class Order
    {
        [PrimaryKey, Identity]
        public double OrderNo { get; set; } // Double
        [Identity]
        public double CustNo { get; set; } // Double
        [Column, Nullable]
        public DateTime? SaleDate { get; set; } // DateTime
        [Column, Nullable]
        public DateTime? ShipDate { get; set; } // DateTime
        [Identity]
        public int EmpNo { get; set; } // Long
        [Column, Nullable]
        public string ShipToContact { get; set; } // text(20)
        [Column, Nullable]
        public string ShipToAddr1 { get; set; } // text(30)
        [Column, Nullable]
        public string ShipToAddr2 { get; set; } // text(30)
        [Column, Nullable]
        public string ShipToCity { get; set; } // text(15)
        [Column, Nullable]
        public string ShipToState { get; set; } // text(20)
        [Column, Nullable]
        public string ShipToZip { get; set; } // text(10)
        [Column, Nullable]
        public string ShipToCountry { get; set; } // text(20)
        [Column, Nullable]
        public string ShipToPhone { get; set; } // text(15)
        [Column, Nullable]
        public string ShipVIA { get; set; } // text(7)
        [Column, Nullable]
        public string PO { get; set; } // text(15)
        [Column, Nullable]
        public string Terms { get; set; } // text(6)
        [Column, Nullable]
        public string PaymentMethod { get; set; } // text(7)
        [Column, Nullable]
        public double? ItemsTotal { get; set; } // Double
        [Column, Nullable]
        public double? TaxRate { get; set; } // Double
        [Column, Nullable]
        public double? Freight { get; set; } // Double
        [Column, Nullable]
        public double? AmountPaid { get; set; } // Double
    }

    [Table("parts")]
    public partial class Part
    {
        [PrimaryKey, Identity]
        public double PartNo { get; set; } // Double
        [Column, Nullable]
        public double? VendorNo { get; set; } // Double
        [Column, Nullable]
        public string Description { get; set; } // text(30)
        [Column, Nullable]
        public double? OnHand { get; set; } // Double
        [Column, Nullable]
        public double? OnOrder { get; set; } // Double
        [Column, Nullable]
        public double? Cost { get; set; } // Double
        [Column, Nullable]
        public double ListPrice { get; set; } // Double
    }

    [Table("vendors")]
    public partial class Vendor
    {
        [PrimaryKey, Identity]
        public double VendorNo { get; set; } // Double
        [Column, Nullable]
        public string VendorName { get; set; } // text(30)
        [Column, Nullable]
        public string Address1 { get; set; } // text(30)
        [Column, Nullable]
        public string Address2 { get; set; } // text(30)
        [Column, Nullable]
        public string City { get; set; } // text(20)
        [Column, Nullable]
        public string State { get; set; } // text(20)
        [Column, Nullable]
        public string Zip { get; set; } // text(10)
        [Column, Nullable]
        public string Country { get; set; } // text(15)
        [Column, Nullable]
        public string Phone { get; set; } // text(15)
        [Column, Nullable]
        public string FAX { get; set; } // text(15)
        [Identity]
        public bool Preferred { get; set; } // Bit
    }

    public static partial class TableExtensions
    {
        public static Country Find(this ITable<Country> table, string Name)
        {
            return table.FirstOrDefault(t =>
                t.Name == Name);
        }

        public static Customer Find(this ITable<Customer> table, double CustNo)
        {
            return table.FirstOrDefault(t =>
                t.CustNo == CustNo);
        }

        public static Employee Find(this ITable<Employee> table, int? EmpNo)
        {
            return table.FirstOrDefault(t =>
                t.EmpNo == EmpNo);
        }

        public static Item Find(this ITable<Item> table, double? OrderNo, double? ItemNo)
        {
            return table.FirstOrDefault(t =>
                t.OrderNo == OrderNo &&
                t.ItemNo == ItemNo);
        }

        public static Order Find(this ITable<Order> table, double OrderNo)
        {
            return table.FirstOrDefault(t =>
                t.OrderNo == OrderNo);
        }

        public static Part Find(this ITable<Part> table, double PartNo)
        {
            return table.FirstOrDefault(t =>
                t.PartNo == PartNo);
        }

        public static Vendor Find(this ITable<Vendor> table, double VendorNo)
        {
            return table.FirstOrDefault(t =>
                t.VendorNo == VendorNo);
        }
    }
}
