//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace ClosedXML.Report.Tests.TestModels
{
    /// <summary>
    /// Database       : dbdemos
    /// Data Source    : ..\..\DB\dbdemos.mdb
    /// Server Version : 04.00.0000
    /// </summary>
    public partial class DbDemos : LinqToDB.Data.DataConnection
    {
        public ITable<country> countries { get { return this.GetTable<country>(); } }
        public ITable<customer> customers { get { return this.GetTable<customer>(); } }
        public ITable<employee> employees { get { return this.GetTable<employee>(); } }
        public ITable<item> items { get { return this.GetTable<item>(); } }
        public ITable<nextcust> nextcusts { get { return this.GetTable<nextcust>(); } }
        public ITable<nextitem> nextitems { get { return this.GetTable<nextitem>(); } }
        public ITable<nextord> nextords { get { return this.GetTable<nextord>(); } }
        public ITable<order> orders { get { return this.GetTable<order>(); } }
        public ITable<part> parts { get { return this.GetTable<part>(); } }
        public ITable<vendor> vendors { get { return this.GetTable<vendor>(); } }

        public DbDemos()
        {
            UpdateMappingSchema();
        }

        public DbDemos(string configuration)
            : base(configuration)
        {
            UpdateMappingSchema();
        }

        private void UpdateMappingSchema()
        {
            this.MappingSchema.SetConverter<long, DateTime?>(ticks => new DateTime(ticks, DateTimeKind.Unspecified));
            this.MappingSchema.SetConverter<string, DateTime?>(ticks =>
            {
                if (string.IsNullOrEmpty(ticks))
                {
                    return null;
                }
                return DateTime.Parse(ticks);
            });
        }
    }

    [Table("country")]
    public partial class country
    {
        [PrimaryKey, Nullable]
        public string Name { get; set; } // text(24)
        [Column, Nullable]
        public string Capital { get; set; } // text(24)
        [Column, Nullable]
        public string Continent { get; set; } // text(24)
        [Column, Nullable]
        public double? Area { get; set; } // Double
        [Column, Nullable]
        public double? Population { get; set; } // Double
    }

    [Table("customer")]
    public partial class customer
    {
        [PrimaryKey, Identity]
        public int CustNo { get; set; } // int
        [Column, Nullable]
        public string Company { get; set; } // text(30)
        [Column, Nullable]
        public string Addr1 { get; set; } // text(30)
        [Column, Nullable]
        public string Addr2 { get; set; } // text(30)
        [Column, Nullable]
        public string City { get; set; } // text(15)
        [Column, Nullable]
        public string State { get; set; } // text(20)
        [Column, Nullable]
        public string Zip { get; set; } // text(10)
        [Column, Nullable]
        public string Country { get; set; } // text(20)
        [Column, Nullable]
        public string Phone { get; set; } // text(15)
        [Column, Nullable]
        public string Fax { get; set; } // text(15)
        [Column, Nullable]
        public double? TaxRate { get; set; } // Double
        [Column, Nullable]
        public string Contact { get; set; } // text(20)
        [Column, Nullable]
        public DateTime? LastInvoiceDate { get; set; } // DateTime
    }

    [Table("employee")]
    public partial class employee
    {
        [PrimaryKey, Nullable]
        public int? EmpNo { get; set; } // Long
        [Column, Nullable]
        public string LastName { get; set; } // text(20)
        [Column, Nullable]
        public string FirstName { get; set; } // text(15)
        [Column, Nullable]
        public string PhoneExt { get; set; } // text(4)
        [Column, Nullable]
        public DateTime? HireDate { get; set; } // DateTime
        [Column, Nullable]
        public double? Salary { get; set; } // Double
    }

    [Table("items")]
    public partial class item
    {
        [PrimaryKey(1), Nullable]
        public double? OrderNo { get; set; } // Double
        [PrimaryKey(2), Nullable]
        public double? ItemNo { get; set; } // Double
        [Column, Nullable]
        public double? PartNo { get; set; } // Double
        [Column, Nullable]
        public int Qty { get; set; } // Long
        [Column, Nullable]
        public double Discount { get; set; } // Double
    }

    [Table("nextcust")]
    public partial class nextcust
    {
        [Column, Nullable]
        public double? NewCust { get; set; } // Double
    }

    [Table("nextitem")]
    public partial class nextitem
    {
        [Column, Nullable]
        public double? NewKey { get; set; } // Double
    }

    [Table("nextord")]
    public partial class nextord
    {
        [Column, Nullable]
        public double? NewKey { get; set; } // Double
    }

    [Table("orders")]
    public partial class order
    {
        [PrimaryKey, Identity]
        public double OrderNo { get; set; } // Double
        [Identity]
        public double CustNo { get; set; } // Double
        [Column, Nullable]
        public DateTime? SaleDate { get; set; } // DateTime
        [Column, Nullable]
        public DateTime? ShipDate { get; set; } // DateTime
        [Identity]
        public int EmpNo { get; set; } // Long
        [Column, Nullable]
        public string ShipToContact { get; set; } // text(20)
        [Column, Nullable]
        public string ShipToAddr1 { get; set; } // text(30)
        [Column, Nullable]
        public string ShipToAddr2 { get; set; } // text(30)
        [Column, Nullable]
        public string ShipToCity { get; set; } // text(15)
        [Column, Nullable]
        public string ShipToState { get; set; } // text(20)
        [Column, Nullable]
        public string ShipToZip { get; set; } // text(10)
        [Column, Nullable]
        public string ShipToCountry { get; set; } // text(20)
        [Column, Nullable]
        public string ShipToPhone { get; set; } // text(15)
        [Column, Nullable]
        public string ShipVIA { get; set; } // text(7)
        [Column, Nullable]
        public string PO { get; set; } // text(15)
        [Column, Nullable]
        public string Terms { get; set; } // text(6)
        [Column, Nullable]
        public string PaymentMethod { get; set; } // text(7)
        [Column, Nullable]
        public double? ItemsTotal { get; set; } // Double
        [Column, Nullable]
        public double? TaxRate { get; set; } // Double
        [Column, Nullable]
        public double? Freight { get; set; } // Double
        [Column, Nullable]
        public double? AmountPaid { get; set; } // Double
    }

    [Table("parts")]
    public partial class part
    {
        [PrimaryKey, Identity]
        public double PartNo { get; set; } // Double
        [Column, Nullable]
        public double? VendorNo { get; set; } // Double
        [Column, Nullable]
        public string Description { get; set; } // text(30)
        [Column, Nullable]
        public double? OnHand { get; set; } // Double
        [Column, Nullable]
        public double? OnOrder { get; set; } // Double
        [Column, Nullable]
        public double? Cost { get; set; } // Double
        [Column, Nullable]
        public double ListPrice { get; set; } // Double
    }

    [Table("vendors")]
    public partial class vendor
    {
        [PrimaryKey, Identity]
        public double VendorNo { get; set; } // Double
        [Column, Nullable]
        public string VendorName { get; set; } // text(30)
        [Column, Nullable]
        public string Address1 { get; set; } // text(30)
        [Column, Nullable]
        public string Address2 { get; set; } // text(30)
        [Column, Nullable]
        public string City { get; set; } // text(20)
        [Column, Nullable]
        public string State { get; set; } // text(20)
        [Column, Nullable]
        public string Zip { get; set; } // text(10)
        [Column, Nullable]
        public string Country { get; set; } // text(15)
        [Column, Nullable]
        public string Phone { get; set; } // text(15)
        [Column, Nullable]
        public string FAX { get; set; } // text(15)
        [Identity]
        public bool Preferred { get; set; } // Bit
    }

    public static partial class TableExtensions
    {
        public static country Find(this ITable<country> table, string Name)
        {
            return table.FirstOrDefault(t =>
                t.Name == Name);
        }

        public static customer Find(this ITable<customer> table, double CustNo)
        {
            return table.FirstOrDefault(t =>
                t.CustNo == CustNo);
        }

        public static employee Find(this ITable<employee> table, int? EmpNo)
        {
            return table.FirstOrDefault(t =>
                t.EmpNo == EmpNo);
        }

        public static item Find(this ITable<item> table, double? OrderNo, double? ItemNo)
        {
            return table.FirstOrDefault(t =>
                t.OrderNo == OrderNo &&
                t.ItemNo == ItemNo);
        }

        public static order Find(this ITable<order> table, double OrderNo)
        {
            return table.FirstOrDefault(t =>
                t.OrderNo == OrderNo);
        }

        public static part Find(this ITable<part> table, double PartNo)
        {
            return table.FirstOrDefault(t =>
                t.PartNo == PartNo);
        }

        public static vendor Find(this ITable<vendor> table, double VendorNo)
        {
            return table.FirstOrDefault(t =>
                t.VendorNo == VendorNo);
        }
    }
}
